### ISSUE TITLE
Emr with custom ami

### ISSUE THREAD

**Issue by Rpambalam** [paeselhz/emr-spark-client#1]
Hi,

I'm facing issue while launching emr with custom ami.

Emr cluster is getting terminated with internal erros.

Please any help on this would be appreciate...

**Comment by paeselhz** [comment]
Hi @Rpambalam , could you provide any more information on the subject? Any traces of the error?

**Comment by Rpambalam** [comment]
Ok,I was trying to create a emr cluster with golden ami. Here I'm using terraform script to launch emr cluster. So while it's launching master node getting terminating and creating cluster again and finally terminating cluster with internal erros.

Connected with support and eam but no luck since it's custom ami.

**Comment by paeselhz** [comment]
Is this terraform script anywhere so I can get a look at what is being deployed?

**Comment by Rpambalam** [comment]
Since it's restricted I'm unable, but the custom ami which was use to launched ec2 and same custom ami was using to launch emr cluster.

I see the script can able to launch master and salve nodes, but master node was terminating every 15min and launching master node again.

Also I see the status of instance-controller was stopped state when I connect to master node..

**Comment by paeselhz** [comment]
I'm sorry, but without any resources, I cannot replicate the issue and try to understand what is causing your EMR cluster to terminate. I'd recommend contact directly through AWS support in this case.
